name: Update Master Data

on:
    push:
        paths:
            - "MASTERDATACSV.csv"
jobs:
    run_script:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Checkout the repository
            - name: Checkout repository
              uses: actions/checkout@v4
            
            # Step 2: Set up Python environment
            - name: Set up Python 3.10
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            
            - name: Convert datafile to internal JSON data
              run: |
                python convertMASTERDATA.py
                # Step 5: Commit and push output file to GitHub
            - name: Commit and push output file to GitHub
              run: |
                git config --global user.name "not ZHD1987E"
                git config --global user.email "zhanghaodong101@outlook.com"

                git add "26th-steps-awardData.dat"
                git commit -m "Generating MasterData!"
                
                git push -f origin main
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}